[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.87.0'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[redirects]]
  from = "https://www.r4wrds.netlify.app/*"
  to = "https://r4wrds.netlify.app/:splat"
  status = 301
  force = true
